#!/bin/bash
#./clean_msg_stats 7 ip:port:pwd ip:port:pwd...
#./clean_offline_msgids 7 ip:port ip:port...
#./clean_offline_msg 7 ip:port ip:port...
#./clean_msg_count 7 ip:port ip:port...

# ./redis-cli -c -h 127.0.0.1  -p  16957 cluster nodes | grep master | awk '{print $2}' | awk -F '@' '{printf $1" "}'
#                   cluster ip     port
